[package]
name = "plotta-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI for plotter control"

[[bin]]
name = "plotta"
path = "src/main.rs"

[dependencies]
drawing-core = { workspace = true }
drawing-text = { path = "../drawing-text" }
drawing-utils = { path = "../drawing-utils" }
drawing-plotter = { workspace = true, features = ["hardware"] }
clap = { workspace = true }
indicatif = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
crossterm = "0.28"
