[package]
name = "sketch-runner"
version.workspace = true
edition.workspace = true

[dependencies]
drawing-core = { workspace = true }
vello = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
